config/routes.rb
PaperclipSampleApp::Application.routes.draw do
  resources :dorms

end

app/models/dorm.rb
class Dorm < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
	validates_attachment_presence :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dorms_controller.rb
class DormsController < ApplicationController
  before_action :set_dorm, only: [:show, :edit, :update, :destroy]

  # GET /dorms
  # GET /dorms.json
  def index
    @dorms = Dorm.all
  end

  # GET /dorms/1
  # GET /dorms/1.json
  def show
  end

  # GET /dorms/new
  def new
    @dorm = Dorm.new
  end

  # GET /dorms/1/edit
  def edit
  end

  # POST /dorms
  # POST /dorms.json
  def create
    @dorm = Dorm.new(dorm_params)

    respond_to do |format|
      if @dorm.save
        format.html { redirect_to @dorm, notice: 'Dorm was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dorm }
      else
        format.html { render action: 'new' }
        format.json { render json: @dorm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dorms/1
  # PATCH/PUT /dorms/1.json
  def update
    respond_to do |format|
      if @dorm.update(dorm_params)
        format.html { redirect_to @dorm, notice: 'Dorm was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dorm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dorms/1
  # DELETE /dorms/1.json
  def destroy
    @dorm.destroy
    respond_to do |format|
      format.html { redirect_to dorms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dorm
      @dorm = Dorm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dorm_params
      params.require(:dorm).permit(:room, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dorms_helper.rb
module DormsHelper
end

app/views/dorms/_form.html.erb
<%= form_for(@dorm, html: { :multipart => true }) do |f| %>
  <% if @dorm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dorm.errors.count, "error") %> prohibited this dorm from being saved:</h2>

      <ul>
      <% @dorm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room %><br>
    <%= f.text_field :room %>

    <%= f.label :avatar, "Room picture" %>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dorms/edit.html.erb
<h1>Editing dorm</h1>

<%= render 'form' %>

<%= link_to 'Show', @dorm %> |
<%= link_to 'Back', dorms_path %>

app/views/dorms/index.html.erb
<h1>Listing dorms</h1>

<table>
  <thead>
    <tr>
      <th>Room</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @dorms.each do |dorm| %>
      <tr>
        <td><%= dorm.room %></td>
        <td><%= link_to 'Show', dorm %></td>
        <td><%= link_to 'Edit', edit_dorm_path(dorm) %></td>
        <td><%= link_to 'Destroy', dorm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dorm', new_dorm_path %>

app/views/dorms/new.html.erb
<h1>New dorm</h1>

<%= render 'form' %>

<%= link_to 'Back', dorms_path %>

app/views/dorms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room:</strong>
  <%= @dorm.room %>
</p>

<%= image_tag @dorm.avatar.url(:medium) %>


<%= link_to 'Edit', edit_dorm_path(@dorm) %> |
<%= link_to 'Back', dorms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PaperclipSampleApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>